comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
ignore:
  - "**/zz_generated.deepcopy.go"